name: Build
run-name: Build
on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install deps
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libx11-dev libgl-dev libglvnd-dev libxrandr-dev libxcursor-dev libxi-dev libxinerama-dev
          version: "@latest"
      - name: Download cosmopolitan
        uses: bjia56/setup-cosmocc@main
        with:
          version: "3.9.7"
      - name: Build
        run: ./build
      - name: Package binaries
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd bin
          zip -r cosmo-sokol.zip *
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            bin/cosmo-sokol.zip
